server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG

spring:
  main:
    banner-mode: off
  application:
    name: client-management
  datasource:
    url: jdbc:postgresql://localhost:5435/cm_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: cm_schema
      connection-init-sql: create schema if not exists cm_schema
      connection-timeout: 10000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: mail.edme.pro
    port: 587
    username: edme_bank_sender@edme.pro
    password: b5wWzrqUqY2pLFYpmA3v
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: false

notification:
  max_attempt: 3
  passport_expire:
    before_months: 3

dadata:
  api:
    authHeader: "Token 50353c0408a3f1a0c2805bd8e0342a2d11a394f2"
    secret: "b7d373eed05ca1b9f3d8550913b1ae99f07fae34"

spectrum_data:
  authHeader: "AR-REST dXNlcl9pbnRlZ3JhdGlvbkBiYWtzZXQ6MTc0MTg1MjgwMDo5OTk5OTk5OTk6MzRKeWpZdXhQWnd6Z0JudThGQi9uQT09"

