server:
  port: 8081
spring:
  main:
    banner-mode: off
  application:
    name: client-management
  datasource:
    url: jdbc:postgresql://localhost:5432/cm_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: cm_schema
      connection-init-sql: create schema if not exists cm_schema
      connection-timeout: 10000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

dadata:
  api:
    url: "https://cleaner.dadata.ru/api/v1/clean/passport"
    key: "50353c0408a3f1a0c2805bd8e0342a2d11a394f2"
    secret: "b7d373eed05ca1b9f3d8550913b1ae99f07fae34"
