version: '3.8'
services:
  postgres:
    container_name: postgres_client_namagement
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cm_db


