version: '3.8'
services:
  postgres:
    container_name: EdMEBank_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cm_db
